### ISSUE TITLE
How to run with ESM

### ISSUE THREAD

**Issue by nuragic** [vadimdemedes/pastel#10]
Hello! I'm wondering if we could run pastel with `esm`: https://www.npmjs.com/package/esm

Something like this: `pastel dev --node-args="-r esm"`

Thanks!

**Comment by vadimdemedes** [comment]
Interesting, currently I don't have a solution for this. Since Pastel transpiles your source files with Babel, what benefits would you get with `esm`?

**Comment by asule90** [comment]
i need this too.

because i think imported es6 modules is not compiled to cjs.
`npm run dev` works without problem.
but when i run the command, i got this :

```
~/project/pouchy-store-cli/node_modules/pouchy-store/index.js:1
(function (exports, require, module, __filename, __dirname) { import PouchyStore from './PouchyStore';
                                                                     ^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

so i guess using `node -r esm` wil resolve this problem. Or am i missing something?

**Comment by nuragic** [comment]
Sorry for the delayed response! About your question about which benefits would you get with esm... well it's just that the code will not be transpiled and instead ran as it is :)
