### ISSUE TITLE
Running builded cli fails

### ISSUE THREAD

**Issue by w01fgang** [vadimdemedes/pastel#14]
After building or running in dev mode, execution of cli fails with an error
```
➜  test hello-person
/private/tmp/test/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: Cannot find module 'pasteljs/boot'
Require stack:
- /private/tmp/test/build/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/private/tmp/test/build/cli.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
```

The name was changed [here](https://github.com/vadimdemedes/pastel/commit/1e71285227aef0bad1d18bd1ae15852e35762225) but it's still `pasteljs` inside the cli.

**Comment by elzup** [comment]
I got Some error.

but, it works when built by [create-pastel-app](https://github.com/vadimdemedes/create-pastel-app). and `create-pastel-app` depends on pastel@1.0.2

**Comment by w01fgang** [comment]
@elzup thanks a lot! It works!

**Comment by vadimdemedes** [comment]
This was an oversight on my side, I thought I published a fix, but I didn't, it stayed in master. Version `1.0.3` is out, which fixes this.
