### ISSUE TITLE
Support for ink 4 (ERR_REQUIRE_ESM error)

### ISSUE THREAD

**Issue by AeonFr** [vadimdemedes/pastel#51]
When creating a new Pastel app, running it for the first time gives an error "ERR_REQUIRE_ESM". The error is fixed by downgrading `ink` to version 3.

## Reproduction:

- `mkdir komcli`
- `cd komcli`
- `npx create-pastel-app`
- `npm run dev`
- Open new terminal and run `komcli --help`

```
❯ komcli --help
internal/modules/cjs/loader.js:1102
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: ~/komcli/node_modules/ink/build/index.js
require() of ES modules is not supported.
require() of ~/komcli/node_modules/ink/build/index.js from ~/komcli/build/cli.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ~/komcli/node_modules/ink/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (~/komcli/build/cli.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_REQUIRE_ESM'
}
```

Notice: other reproduction steps would be to create a new project with a package.json file looking like this: (it's what create-pastel-app does)

```
{
	"name": "komcli",
	"version": "0.0.0",
	"license": "MIT",
	"bin": "./build/cli.js",
	"engines": {
		"node": ">=8"
	},
	"scripts": {
		"dev": "pastel dev",
		"build": "pastel build",
		"prepare": "pastel build"
	},
	"files": [
		"build"
	],
	"dependencies": {
		"ink": "^4.0.0",
		"pastel": "^1.1.1",
		"prop-types": "^15.8.1",
		"react": "^18.2.0"
	},
	"devDependencies": {}
}
```

I believe that in order to support Ink 4, `package.json` should have `type: "module"` and Pastel should start bundling code in ESM format.

I'm willing to try and submit a PR for this

**Comment by vadimdemedes** [comment]
I'm working on a completely new version of Pastel, which will work with Ink 4. Stay tuned.
